name: nightly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $( echo ${{ github.event.head_commit.id }} | cut -c1-7 )
      COMMIT: $( jq -Rsa . <<< "${{ github.event.head_commit.message }}"  | tail -c +2 | head -c -2 )
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Cook Env
        run: |
          COMMIT=${{ env.COMMIT }}
          VERSION=${{ env.VERSION }}
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.PASSWORD }} \
          -Pandroid.injected.signing.key.alias=key0 \
          -Pandroid.injected.signing.key.password=${{ secrets.PASSWORD }}
          cp app/build/outputs/apk/debug/app-debug.apk app/build/yt-${{ env.VERSION }}.eapk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: app/build/yt-${{ env.VERSION }}.eapk
  
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${VERSION}
          body: ${COMMIT}
          name: "Echo Extension : Youtube Music ${VERSION}"
          files: app/build/yt-${VERSION}.eapk

      - name: Upload APK to Discord
        shell: bash
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          message=$(echo "@everyone **${{ env.VERSION }}**\n${{ env.COMMIT }}")
          curl -F "payload_json={\"content\":\"${message}\"}" \
          -F "file=@app/build/yt-${{ env.VERSION }}.eapk" \
          ${{ env.WEBHOOK }}
          
      - name: Upload APK to Telegram
        shell: bash
        env:
          BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          message=$(printf "*Youtube Extension*\n${{ env.COMMIT }}" | sed 's/[~>|.!+-=#]/\\&/g')
          curl -F "chat_id=${{ env.CHANNEL_ID }}" \
          -F "document=@app/build/yt-${{ env.VERSION }}.eapk" \
          -F "caption=${message}" \
          -F "parse_mode=MarkdownV2" \
          https://api.telegram.org/bot${{ env.BOT_ID }}/sendDocument
